runner:
  launcher: python
  module: alphaapollo.core.generation.verl.trainer.main_ppo
  overrides:
    - algorithm.adv_estimator=grpo
    - data.train_files=/root/autodl-tmp/AlphaApollo-Visual/datasets/data/test-00000-of-00002-6b81bd7f7e2065e6.parquet
    - data.val_files=/root/autodl-tmp/AlphaApollo-Visual/datasets/data/testmini-00000-of-00001-725687bf7a18d64b.parquet
    - data.train_batch_size=2
    - data.val_batch_size=2
    - data.max_prompt_length=4096
    - data.max_response_length=1024
    - data.filter_overlong_prompts=False
    - data.truncation=right
    - data.return_raw_chat=True
    - data.prompt_key=query
    - data.image_key=image
    - actor_rollout_ref.model.path=/root/autodl-tmp/qwen/qwen3_vl_2b
    - actor_rollout_ref.actor.optim.lr=1e-6
    - actor_rollout_ref.model.use_remove_padding=True
    - actor_rollout_ref.actor.ppo_mini_batch_size=4
    - actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=2
    - actor_rollout_ref.actor.use_kl_loss=True
    - actor_rollout_ref.actor.kl_loss_coef=0.01
    - actor_rollout_ref.actor.kl_loss_type=low_var_kl
    - actor_rollout_ref.model.enable_gradient_checkpointing=True
    - actor_rollout_ref.actor.fsdp_config.param_offload=False
    - actor_rollout_ref.actor.fsdp_config.optimizer_offload=False
    - actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=2
    - actor_rollout_ref.rollout.tensor_model_parallel_size=1
    - actor_rollout_ref.rollout.name=vllm
    - actor_rollout_ref.rollout.gpu_memory_utilization=0.5
    - actor_rollout_ref.rollout.enable_chunked_prefill=False
    - actor_rollout_ref.rollout.enforce_eager=False
    - actor_rollout_ref.rollout.free_cache_engine=False
    - actor_rollout_ref.rollout.limit_images=1
    - actor_rollout_ref.rollout.val_kwargs.temperature=0.4
    - actor_rollout_ref.rollout.val_kwargs.do_sample=True
    - actor_rollout_ref.ref.log_prob_max_token_len_per_gpu=32768
    - actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2
    - actor_rollout_ref.ref.fsdp_config.param_offload=True
    - actor_rollout_ref.actor.use_invalid_action_penalty=True
    - actor_rollout_ref.actor.invalid_action_penalty_coef=0.1
    - algorithm.use_kl_in_reward=False
    - env.env_name=informal_math_training
    - env.seed=0
    - env.max_steps=4
    - env.history_length=4
    - env.rollout.n=1
    - env.resources_per_worker.num_cpus=0.1
    - env.informal_math.memory_type=simple
    - env.informal_math.log_requests=false
    - env.informal_math.python_code_timeout=30
    - env.informal_math.enable_python_code=true
    - env.informal_math.enable_local_rag=false
    - trainer.critic_warmup=0
    - trainer.logger=['console','wandb']
    - trainer.project_name=alphaapollo_visual_local
    - trainer.experiment_name=grpo_qwen3_vl_2b_local
    - trainer.n_gpus_per_node=1
    - trainer.nnodes=1
    - trainer.save_freq=500
    - trainer.test_freq=100
    - trainer.total_epochs=1
    - trainer.val_before_train=False
